map $request_uri $lb_mode {
    default active-passive;
}

upstream auth_pool {
    server auth-service:5001 max_fails=1 fail_timeout=2s;
    server auth-service-b:5001 backup;
}

upstream links_pool {
    server links-service:5002 max_fails=1 fail_timeout=2s;
    server links-service-b:5002 backup;
}

upstream analytics_pool {
    server analytics-service:5003 max_fails=1 fail_timeout=2s;
    server analytics-service-b:5003 backup;
}
