events {}

http {
    upstream auth_pool {
        server auth-service:5001 max_fails=1 fail_timeout=2s;
        server auth-service-b:5001 backup;
    }

    upstream links_pool {
        server links-service:5002 max_fails=1 fail_timeout=2s;
        server links-service-b:5002 backup;
    }

    upstream analytics_pool {
        server analytics-service:5003 max_fails=1 fail_timeout=2s;
        server analytics-service-b:5003 backup;
    }

    upstream frontend_pool {
        server frontend:80;
    }

    server {
        listen 80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /api/auth/ {
            rewrite ^/api(/.*)$ $1 break;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_pass http://auth_pool;
            add_header X-LB-Mode active-passive always;
        }

        location /api/admin/ {
            rewrite ^/api(/.*)$ $1 break;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_pass http://auth_pool;
            add_header X-LB-Mode active-passive always;
        }

        location ~ ^/api/links/[^/]+/stats/?$ {
            rewrite ^/api(/.*)$ $1 break;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_pass http://analytics_pool;
            add_header X-LB-Mode active-passive always;
        }

        location /api/links/ {
            rewrite ^/api(/.*)$ $1 break;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_pass http://links_pool;
            add_header X-LB-Mode active-passive always;
        }

        location /api/links {
            rewrite ^/api(/.*)$ $1 break;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_pass http://links_pool;
            add_header X-LB-Mode active-passive always;
        }

        location /s/ {
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_pass http://links_pool;
            add_header X-LB-Mode active-passive always;
        }

        location / {
            proxy_pass http://frontend_pool;
        }
    }
}